/**
 * D1 Seed Script — generates idempotent SQL from an R2 index.json file.
 *
 * Usage:
 *   npx tsx scripts/seed-d1.ts scripts/sample-index.json > seed.sql
 *   wrangler d1 execute trueroute-d1 --file=seed.sql
 *
 * The script validates the input against RegionIndexSchema, then produces
 * SQL that can be piped directly into `wrangler d1 execute`.
 *
 * Idempotency: the generated SQL deletes all existing region_files and
 * regions for the country before re-inserting, wrapped in a transaction.
 */

import { readFileSync } from 'node:fs'
import { RegionIndexSchema } from '../src/schemas/regions.schema'
import type { Region, Asset } from '../src/schemas/regions.schema'

const COUNTRY_CODE = 'UA'
const COUNTRY_NAME = 'Ukraine'
const COUNTRY_NAME_UK = 'Україна'

/** Escape a string for use in a SQL single-quoted literal. */
export function escapeSql(value: string): string {
  return value.replace(/'/g, "''")
}

const FILE_TYPES = ['maps', 'geocode', 'poi', 'routing'] as const

function generateRegionFilesSql(region: Region): string {
  const lines: string[] = []
  const assets = region.assets as Record<string, Asset | undefined>

  for (const fileType of FILE_TYPES) {
    const asset = assets[fileType]
    if (!asset) continue

    lines.push(
      `INSERT INTO region_files (region_id, file_type, url, size_bytes, sha256, generated_at)` +
        ` VALUES (` +
        `(SELECT id FROM regions WHERE code = '${escapeSql(region.id)}' AND country_id = (SELECT id FROM countries WHERE code = '${COUNTRY_CODE}')),` +
        ` '${fileType}',` +
        ` '${escapeSql(asset.url)}',` +
        ` ${asset.sizeBytes},` +
        ` '${escapeSql(asset.sha256)}',` +
        ` '${escapeSql(asset.generatedAt)}'` +
        `);`,
    )
  }

  return lines.join('\n')
}

/**
 * Generate a complete, idempotent SQL seed from a parsed (but not yet
 * validated) index.json object.
 *
 * Throws a ZodError if the input does not match RegionIndexSchema.
 */
export function generateSeedSql(input: unknown): string {
  // Strip non-schema fields (e.g. _comment) before validation
  const raw = input as Record<string, unknown>
  const cleaned = {
    version: raw.version,
    generatedAt: raw.generatedAt,
    regions: raw.regions,
  }

  const index = RegionIndexSchema.parse(cleaned)

  const lines: string[] = [
    '-- Auto-generated by scripts/seed-d1.ts',
    `-- Source: index.json (${index.regions.length} regions, generated ${index.generatedAt})`,
    '',
    '-- Note: D1 via wrangler handles transactions automatically (no explicit transaction statements needed).',
    '',
    '-- 1. Upsert country (UPDATE in place — preserves id so FK references from regions are not broken)',
    `INSERT INTO countries (code, name, name_uk, enabled)` +
      ` VALUES ('${COUNTRY_CODE}', '${escapeSql(COUNTRY_NAME)}', '${escapeSql(COUNTRY_NAME_UK)}', 1)` +
      ` ON CONFLICT(code) DO UPDATE SET name = excluded.name, name_uk = excluded.name_uk, enabled = excluded.enabled;`,
    '',
    '-- 2. Delete existing data for this country (idempotency)',
    `DELETE FROM region_files WHERE region_id IN (SELECT id FROM regions WHERE country_id = (SELECT id FROM countries WHERE code = '${COUNTRY_CODE}'));`,
    `DELETE FROM regions WHERE country_id = (SELECT id FROM countries WHERE code = '${COUNTRY_CODE}');`,
    '',
    '-- 3. Insert regions and their files',
  ]

  for (const region of index.regions) {
    lines.push('')
    lines.push(`-- Region: ${region.name} (${region.nameUk})`)
    lines.push(
      `INSERT INTO regions (country_id, code, name, name_uk)` +
        ` VALUES (` +
        `(SELECT id FROM countries WHERE code = '${COUNTRY_CODE}'),` +
        ` '${escapeSql(region.id)}',` +
        ` '${escapeSql(region.name)}',` +
        ` '${escapeSql(region.nameUk)}'` +
        `);`,
    )
    lines.push(generateRegionFilesSql(region))
  }

  lines.push('')

  return lines.join('\n')
}

// CLI entry point — only runs when executed directly
if (process.argv[1] && process.argv[1].includes('seed-d1')) {
  const inputPath = process.argv[2]
  if (!inputPath) {
    process.stderr.write('Usage: npx tsx scripts/seed-d1.ts <path-to-index.json>\n')
    process.exit(1)
  }

  const raw = JSON.parse(readFileSync(inputPath, 'utf-8'))
  const sql = generateSeedSql(raw)
  process.stdout.write(sql)
}
